
import strapiFactory from '@strapi/strapi';

async function generateToken() {
    const strapi = await strapiFactory().load();

    try {
        const tokenService = strapi.admin.services['api-token'];

        if (!tokenService) {
            console.error('API Token service not found');
            process.exit(1);
        }

        const tokenName = 'Frontend Check ' + Date.now();

        // Check if token already exists (optional, but good practice)
        // For now, just create a new one to be sure.

        const token = await tokenService.create({
            name: tokenName,
            type: 'cupcake', // 'custom' logic or specific type? V5 uses 'full-access' usually or 'read-only' mapped to types.
            // Actually in v4/v5 content-api permissions are handled via 'type'.
            // Let's check the schema or docs. 'full-access' is a common type.
            // Wait, let's try 'full-access'.
            description: 'Generated by migration script',
            lifespan: null, // Unlimited
            permissions: [], // Full access doesn't need explicit permissions list usually
            type: 'full-access',
        });

        console.log('__TOKEN_START__');
        console.log(token.accessKey);
        console.log('__TOKEN_END__');

    } catch (error) {
        console.error('Error generating token:', error);
    } finally {
        // strapi.stop() or destroy might be needed, or just exit
        process.exit(0);
    }
}

generateToken();
