
const { createStrapi } = require('@strapi/strapi');

async function generateToken() {
    const app = await createStrapi().load();

    try {
        const tokenService = strapi.admin.services['api-token'];

        if (!tokenService) {
            console.error('API Token service not found');
            process.exit(1);
        }

        const tokenName = 'Frontend Check ' + Date.now();

        const token = await tokenService.create({
            name: tokenName,
            type: 'full-access',
            description: 'Generated by migration script',
            lifespan: null, // Unlimited
            permissions: [],
        });

        console.log('__TOKEN_START__');
        console.log(token.accessKey);
        console.log('__TOKEN_END__');

    } catch (error) {
        console.error('Error generating token:', error);
    } finally {
        process.exit(0);
    }
}

generateToken();
