-- Exact per-service body-style prices with immutable booking price snapshots.

CREATE TABLE IF NOT EXISTS public.service_body_style_prices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id INTEGER NOT NULL REFERENCES public.services(id) ON DELETE CASCADE,
  body_style TEXT NOT NULL CHECK (
    body_style IN ('sedan', 'coupe', 'suv', 'large_suv', 'pickup', 'minivan', 'van', 'other')
  ),
  price_cents INTEGER NOT NULL CHECK (price_cents > 0),
  currency TEXT NOT NULL DEFAULT 'usd' CHECK (currency ~ '^[a-z]{3}$'),
  stripe_price_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT service_body_style_prices_service_style_key UNIQUE (service_id, body_style)
);

CREATE INDEX IF NOT EXISTS idx_service_body_style_prices_service_id
  ON public.service_body_style_prices(service_id);

CREATE OR REPLACE FUNCTION public.set_service_body_style_prices_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS service_body_style_prices_set_updated_at
  ON public.service_body_style_prices;
CREATE TRIGGER service_body_style_prices_set_updated_at
BEFORE UPDATE ON public.service_body_style_prices
FOR EACH ROW
EXECUTE FUNCTION public.set_service_body_style_prices_updated_at();

ALTER TABLE public.service_body_style_prices ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Active service body-style prices are publicly readable"
  ON public.service_body_style_prices;
CREATE POLICY "Active service body-style prices are publicly readable"
  ON public.service_body_style_prices
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.services
      WHERE services.id = service_body_style_prices.service_id
        AND services.is_active = true
    )
  );

GRANT SELECT ON public.service_body_style_prices TO anon, authenticated;

ALTER TABLE public.bookings
  ADD COLUMN IF NOT EXISTS vehicle_body_style TEXT CHECK (
    vehicle_body_style IS NULL OR
    vehicle_body_style IN ('sedan', 'coupe', 'suv', 'large_suv', 'pickup', 'minivan', 'van', 'other')
  ),
  ADD COLUMN IF NOT EXISTS service_price_cents INTEGER CHECK (
    service_price_cents IS NULL OR service_price_cents >= 0
  ),
  ADD COLUMN IF NOT EXISTS add_ons_price_cents INTEGER CHECK (
    add_ons_price_cents IS NULL OR add_ons_price_cents >= 0
  ),
  ADD COLUMN IF NOT EXISTS total_price_cents INTEGER CHECK (
    total_price_cents IS NULL OR total_price_cents >= 0
  ),
  ADD COLUMN IF NOT EXISTS pricing_revision TEXT;

COMMENT ON COLUMN public.bookings.vehicle_body_style IS
  'Canonical body style used for the authoritative price at booking time.';
COMMENT ON COLUMN public.bookings.service_price_cents IS
  'Service price snapshot, after applying any body-style override.';
COMMENT ON COLUMN public.bookings.add_ons_price_cents IS
  'Per-vehicle add-on price snapshot.';
COMMENT ON COLUMN public.bookings.total_price_cents IS
  'Per-vehicle authoritative total snapshot.';
COMMENT ON COLUMN public.bookings.pricing_revision IS
  'Deterministic revision of the authoritative service, override, and add-on prices.';
