/**
 * POST /api/booking/create-with-payment
 *
 * Atomic replacement for the two-step booking/create → payments/create-intent flow.
 * Creates a booking record and a Stripe PaymentIntent in a single request.
 *
 * If Stripe fails the booking is deleted from the DB before returning the error,
 * preventing orphaned bookings that were never paid for.
 *
 * Returns: { confirmationCode, clientSecret, paymentIntentId, bookingId }
 */

import { NextRequest, NextResponse } from 'next/server';
import * as Sentry from '@sentry/nextjs';
import { z } from 'zod';
import { createClient, createServiceClient } from '@/lib/supabase/server';
import { createPaymentIntent } from '@/lib/stripe/server';
import { rateLimit } from '@/lib/rateLimit';
import { getQStashClient, SITE_URL } from '@/lib/qstash';

const CreateWithPaymentSchema = z.object({
    serviceName: z.string().min(1, 'Service name is required'),
    date: z.string().min(1, 'Date is required').refine((val) => {
        const d = new Date(val);
        return !isNaN(d.getTime());
    }, 'Date must be a valid date string'),
    timeWindow: z.string().regex(/^(\d{2}:\d{2}|morning|afternoon|evening)$/, 'Time window must be HH:MM or morning/afternoon/evening'),
    customerName: z.string().min(1, 'Customer name is required'),
    customerEmail: z.string().email('Invalid email address'),
    customerPhone: z.string().optional().default(''),
    address: z.string().min(1, 'Address is required'),
    city: z.string().optional().default(''),
    state: z.string().optional().default('FL'),
    zipCode: z.string().regex(/^\d{5}$/, 'ZIP code must be exactly 5 digits').optional(),
    vehicleMake: z.string().optional(),
    vehicleModel: z.string().optional(),
    vehicleYear: z.union([z.string(), z.number()]).optional(),
    vehicleColor: z.string().optional(),
    vehicles: z.array(z.object({
        make: z.string().optional(),
        model: z.string().optional(),
        year: z.union([z.string(), z.number()]).optional(),
        color: z.string().optional(),
    })).optional(),
    subtotal: z.number().optional(),
    serviceFee: z.number().optional(),
    total: z.number().positive('Total must be a positive number'),
    perVehicleTotal: z.number().optional(),
    specialInstructions: z.string().optional().default(''),
    selectedAddOns: z.array(z.object({
        name: z.string(),
        price: z.number(),
    })).optional(),
    currency: z.string().optional().default('usd'),
    locale: z.enum(['en', 'es']).optional().default('en'),
});

// confirmation_code is now auto-generated by Postgres sequence (DEFAULT generate_booking_code())

export async function POST(req: NextRequest) {
    if (await rateLimit(req, { maxRequests: 5, windowMs: 60_000, keyPrefix: 'booking-create' })) {
        return NextResponse.json({ error: 'Too many requests. Please try again in a minute.' }, { status: 429 });
    }

    // Require authentication — no guest bookings
    const supabaseAuth = await createClient();
    const { data: { user } } = await supabaseAuth.auth.getUser();
    if (!user) {
        return NextResponse.json({ error: 'Authentication required. Please log in to book.' }, { status: 401 });
    }

    let rawBody: unknown;
    try {
        rawBody = await req.json();
    } catch {
        return NextResponse.json({ error: 'Invalid request body' }, { status: 400 });
    }

    const parsed = CreateWithPaymentSchema.safeParse(rawBody);
    if (!parsed.success) {
        const fieldErrors = parsed.error.issues.map((e) => ({
            field: e.path.join('.'),
            message: e.message,
        }));
        return NextResponse.json({ error: 'Validation failed', details: fieldErrors }, { status: 400 });
    }

    const {
        date, timeWindow, address, city, state, zipCode,
        customerName, customerEmail, customerPhone,
        specialInstructions, subtotal, serviceFee, total,
        perVehicleTotal,
        serviceName, selectedAddOns: selectedAddOnsInput,
        vehicles: vehiclesInput,
        vehicleMake, vehicleModel, vehicleYear, vehicleColor,
        currency,
        locale,
    } = parsed.data;

    // Build vehicles array — backwards compat: if no vehicles array, use single vehicle fields
    const vehicles = (vehiclesInput && vehiclesInput.length > 0)
        ? vehiclesInput
        : [{ make: vehicleMake, model: vehicleModel, year: vehicleYear, color: vehicleColor }];

    const vehicleCount = vehicles.length;

    const supabase = createServiceClient();

    // ── Server-side price validation ────────────────────────────────────────
    // Never trust client-submitted totals. Re-derive from DB prices.
    const { data: dbService } = await supabase
        .from('services')
        .select('id, base_price')
        .eq('name', serviceName)
        .eq('is_active', true)
        .single();

    if (!dbService) {
        return NextResponse.json({ error: 'Service not found or inactive' }, { status: 400 });
    }

    let serverAddOnsTotal = 0;
    const verifiedAddOns: { name: string; price: number }[] = [];
    if (selectedAddOnsInput && selectedAddOnsInput.length > 0) {
        const addOnNames = selectedAddOnsInput.map(a => a.name);
        const { data: dbAddOns } = await supabase
            .from('add_ons')
            .select('name, price')
            .in('name', addOnNames)
            .eq('is_active', true);

        if (dbAddOns) {
            for (const addon of dbAddOns) {
                serverAddOnsTotal += Number(addon.price);
                verifiedAddOns.push({ name: addon.name, price: Number(addon.price) });
            }
        }
    }

    const serverPerVehicle = Number(dbService.base_price) + serverAddOnsTotal;
    const serverTotal = Math.round(serverPerVehicle * vehicleCount * 100) / 100;
    const perVehicleAmount = serverPerVehicle;

    // Allow a small tolerance ($0.02) for floating-point rounding
    if (Math.abs(serverTotal - total) > 0.02) {
        console.warn(
            `create-with-payment: price mismatch — client sent $${total}, server calculated $${serverTotal} ` +
            `(service: $${dbService.base_price}, addOns: $${serverAddOnsTotal}, vehicles: ${vehicleCount})`
        );
        return NextResponse.json({
            error: 'Price has changed. Please go back and review your order.',
            serverTotal,
        }, { status: 409 });
    }

    const amountCents = Math.round(serverTotal * 100);
    if (amountCents <= 0) {
        return NextResponse.json({ error: 'Invalid booking total' }, { status: 400 });
    }
    const userId = user?.id || null;

    // Generate a group ID when booking multiple vehicles in one appointment
    const bookingGroupId = vehicleCount > 1 ? crypto.randomUUID() : null;

    // ── Step 1: Create booking(s) — one per vehicle ─────────────────────────
    const bookingRows = vehicles.map(v => ({
        user_id: userId,
        status: 'pending_payment' as const,
        payment_status: 'unpaid' as const,
        date,
        time_window: timeWindow,
        address,
        city: city || '',
        state: state || 'FL',
        zip_code: zipCode,
        customer_name: customerName,
        customer_email: customerEmail,
        customer_phone: customerPhone || '',
        special_instructions: specialInstructions || '',
        locale,
        subtotal: perVehicleAmount,
        service_fee: 0,
        total_amount: perVehicleAmount,
        service_name: serviceName || null,
        service_id: dbService.id,
        selected_add_ons: verifiedAddOns,
        vehicle_make: v.make || null,
        vehicle_model: v.model || null,
        vehicle_year: v.year || null,
        vehicle_color: v.color || null,
        ...(bookingGroupId ? { booking_group_id: bookingGroupId } : {}),
    }));

    const { data: bookings, error: bookingError } = await supabase
        .from('bookings')
        .insert(bookingRows)
        .select();

    if (bookingError || !bookings || bookings.length === 0) {
        console.error('create-with-payment: booking insert failed:', bookingError);
        return NextResponse.json({ error: 'Failed to create booking' }, { status: 500 });
    }

    const bookingIds = bookings.map(b => String(b.id));
    const primaryBookingId = bookingIds[0];

    // ── Step 2: Create Stripe PaymentIntent ──────────────────────────────────
    // If this fails, we delete all bookings so no orphaned records are left.
    let paymentIntent: { clientSecret: string | null; paymentIntentId: string; amount: number };
    try {
        paymentIntent = await createPaymentIntent({
            amount: amountCents,
            bookingId: primaryBookingId,
            customerId: customerEmail ?? 'guest',
            currency,
        });
    } catch (stripeErr) {
        // Rollback: remove all bookings we just created
        await supabase.from('bookings').delete().in('id', bookings.map(b => b.id));

        console.error('create-with-payment: Stripe failed, bookings rolled back:', stripeErr);
        return NextResponse.json(
            { error: 'Payment setup failed. Please try again or contact support.' },
            { status: 502 }
        );
    }

    // ── Step 3: Persist payment intent ID on all bookings ────────────────────
    await supabase
        .from('bookings')
        .update({ payment_intent_id: paymentIntent.paymentIntentId })
        .in('id', bookings.map(b => b.id));

    // ── Step 4: Customer confirmation email only ──────────────────────────────
    // Contractor notifications fire from the webhook (payment_intent.amount_capturable_updated)
    // AFTER payment is confirmed, so contractors only see jobs that have been paid for.
    notifyCustomer(bookings[0], serviceName ?? 'Detailing Service').catch(
        (err) => {
            console.error('create-with-payment: customer notification failed:', err);
            Sentry.captureException(err, { tags: { context: 'customer_notification', bookingId: bookings[0].id } });
        }
    );

    // ── Step 5: Enqueue payment reminder emails via QStash ───────────────────
    // Each reminder fires only if the booking is still pending_payment at that time.
    schedulePaymentReminders(bookings[0].id).catch(
        (err) => console.error('create-with-payment: QStash scheduling failed:', err)
    );

    const confirmationCodes = bookings.map(b => b.confirmation_code);

    return NextResponse.json({
        success: true,
        confirmationCode: confirmationCodes[0],
        confirmationCodes,
        clientSecret: paymentIntent.clientSecret,
        paymentIntentId: paymentIntent.paymentIntentId,
        bookingId: primaryBookingId,
        bookingIds,
        bookingGroupId,
        vehicleCount,
    });
}

// ── Schedule escalating payment reminders via Upstash QStash ─────────────────
// Delays: 15 min → 2 hours → 24 hours

async function schedulePaymentReminders(bookingId: number) {
    const qstash = getQStashClient();
    const url = `${SITE_URL}/api/booking/payment-reminder`;

    const reminders: Array<{ delay: number; reminderNumber: 1 | 2 | 3 }> = [
        { delay: 15 * 60,       reminderNumber: 1 }, // 15 minutes
        { delay: 2 * 60 * 60,   reminderNumber: 2 }, // 2 hours
        { delay: 24 * 60 * 60,  reminderNumber: 3 }, // 24 hours
    ];

    await Promise.all(
        reminders.map(({ delay, reminderNumber }) =>
            qstash.publishJSON({
                url,
                delay,
                body: { bookingId, reminderNumber },
            })
        )
    );

    console.log(`Payment reminders scheduled for booking ${bookingId}`);
}

// ── Customer confirmation email only (booking pending payment) ────────────────

async function notifyCustomer(
    booking: Record<string, unknown>,
    resolvedServiceName: string,
) {
    const bookingWithService = { ...booking, service_name: resolvedServiceName };
    const { notify } = await import('@/lib/notifications');
    await notify({ type: 'booking.created', booking: bookingWithService });
}
