/**
 * POST /api/booking/create-with-payment
 *
 * Atomic replacement for the two-step booking/create → payments/create-intent flow.
 * Creates a booking record and a Stripe PaymentIntent in a single request.
 *
 * If Stripe fails the booking is deleted from the DB before returning the error,
 * preventing orphaned bookings that were never paid for.
 *
 * Returns: { confirmationCode, clientSecret, paymentIntentId, bookingId }
 */

import { NextRequest, NextResponse } from 'next/server';
import * as Sentry from '@sentry/nextjs';
import { z } from 'zod';
import { createClient, createServiceClient } from '@/lib/supabase/server';
import { createPaymentIntent } from '@/lib/stripe/server';
import { rateLimit } from '@/lib/rateLimit';
import { getQStashClient, SITE_URL } from '@/lib/qstash';
import {
    BODY_STYLES,
    centsToDollars,
    decimalToCents,
    formatCents,
    PricingInputError,
    resolveBookingPrice,
    type ResolvedBookingPrice,
} from '@/lib/pricing';

const bodyStyleSchema = z.enum([...BODY_STYLES, 'truck'] as const);

const CreateWithPaymentSchema = z.object({
    serviceId: z.union([z.string().trim().min(1), z.number().int().positive()]).optional(),
    serviceName: z.string().trim().min(1).max(200).optional(),
    date: z.string().min(1, 'Date is required').refine((val) => {
        const d = new Date(val);
        return !isNaN(d.getTime());
    }, 'Date must be a valid date string'),
    timeWindow: z.string().regex(/^(\d{2}:\d{2}|morning|afternoon|evening)$/, 'Time window must be HH:MM or morning/afternoon/evening'),
    customerName: z.string().min(1, 'Customer name is required'),
    customerEmail: z.string().email('Invalid email address'),
    customerPhone: z.string().optional().default(''),
    address: z.string().min(1, 'Address is required'),
    city: z.string().optional().default(''),
    state: z.string().optional().default('FL'),
    zipCode: z.string().regex(/^\d{5}$/, 'ZIP code must be exactly 5 digits').optional(),
    vehicleMake: z.string().optional(),
    vehicleModel: z.string().optional(),
    vehicleYear: z.union([z.string(), z.number()]).optional(),
    vehicleColor: z.string().optional(),
    vehicles: z.array(z.object({
        make: z.string().optional(),
        model: z.string().optional(),
        year: z.union([z.string(), z.number()]).optional(),
        color: z.string().optional(),
        vehicleId: z.string().min(1).optional(),
        bodyStyle: bodyStyleSchema,
    })).min(1).max(10).optional(),
    subtotal: z.number().optional(),
    serviceFee: z.number().optional(),
    total: z.number().positive('Total must be a positive number'),
    perVehicleTotal: z.number().optional(),
    specialInstructions: z.string().optional().default(''),
    selectedAddOns: z.array(z.object({
        name: z.string(),
        price: z.number(),
    })).optional(),
    addOnIds: z.array(z.union([z.string().min(1), z.number().int().positive()])).optional(),
    pricingRevision: z.string().regex(/^v1_[a-f0-9]{64}$/).optional(),
    bodyStyle: bodyStyleSchema.optional(),
    currency: z.literal('usd').optional().default('usd'),
    locale: z.enum(['en', 'es']).optional().default('en'),
}).refine((value) => value.serviceId !== undefined || value.serviceName !== undefined, {
    message: 'Service ID or service name is required',
    path: ['serviceId'],
}).refine((value) => Boolean(value.vehicles?.length || value.bodyStyle), {
    message: 'A body style is required for every vehicle',
    path: ['vehicles'],
});

// confirmation_code is now auto-generated by Postgres sequence (DEFAULT generate_booking_code())

export async function POST(req: NextRequest) {
    if (await rateLimit(req, { maxRequests: 5, windowMs: 60_000, keyPrefix: 'booking-create' })) {
        return NextResponse.json({ error: 'Too many requests. Please try again in a minute.' }, { status: 429 });
    }

    // Require authentication — no guest bookings
    const supabaseAuth = await createClient();
    const { data: { user } } = await supabaseAuth.auth.getUser();
    if (!user) {
        return NextResponse.json({ error: 'Authentication required. Please log in to book.' }, { status: 401 });
    }

    let rawBody: unknown;
    try {
        rawBody = await req.json();
    } catch {
        return NextResponse.json({ error: 'Invalid request body' }, { status: 400 });
    }

    const parsed = CreateWithPaymentSchema.safeParse(rawBody);
    if (!parsed.success) {
        const fieldErrors = parsed.error.issues.map((e) => ({
            field: e.path.join('.'),
            message: e.message,
        }));
        return NextResponse.json({ error: 'Validation failed', details: fieldErrors }, { status: 400 });
    }

    const {
        date, timeWindow, address, city, state, zipCode,
        customerName, customerEmail, customerPhone,
        specialInstructions, total,
        serviceId,
        serviceName, selectedAddOns: selectedAddOnsInput,
        addOnIds,
        vehicles: vehiclesInput,
        vehicleMake, vehicleModel, vehicleYear, vehicleColor,
        currency, pricingRevision, bodyStyle,
        locale,
    } = parsed.data;

    // Build vehicles array — backwards compat: if no vehicles array, use single vehicle fields
    const vehicles = (vehiclesInput && vehiclesInput.length > 0)
        ? vehiclesInput
        : [{
            make: vehicleMake,
            model: vehicleModel,
            year: vehicleYear,
            color: vehicleColor,
            bodyStyle: bodyStyle!,
        }];

    const vehicleCount = vehicles.length;

    const supabase = createServiceClient();

    // Never trust client-submitted totals. Both quote and charge use this resolver.
    let quote: ResolvedBookingPrice;
    try {
        quote = await resolveBookingPrice({
            serviceId,
            serviceName,
            addOnIds,
            addOnNames: addOnIds?.length ? [] : selectedAddOnsInput?.map((addOn) => addOn.name),
            vehicles: vehicles.map((vehicle) => ({
                bodyStyle: vehicle.bodyStyle,
                vehicleId: vehicle.vehicleId,
            })),
            currency,
        }, supabase);
    } catch (error) {
        if (error instanceof PricingInputError) {
            return NextResponse.json({ error: error.message }, { status: 400 });
        }
        throw error;
    }

    let submittedTotalCents: number;
    try {
        submittedTotalCents = decimalToCents(total);
    } catch {
        return NextResponse.json({ error: 'Invalid booking total' }, { status: 400 });
    }
    if ((pricingRevision !== undefined && pricingRevision !== quote.pricingRevision) ||
        submittedTotalCents !== quote.totalCents) {
        console.warn(
            `create-with-payment: stale price — client revision ${pricingRevision ?? 'none'}, ` +
            `server revision ${quote.pricingRevision}`
        );
        return NextResponse.json({
            error: 'Price has changed. Please go back and review your order.',
            code: 'PRICE_CHANGED',
            previousTotalCents: submittedTotalCents,
            serverTotal: centsToDollars(quote.totalCents),
            quote: {
                ...quote,
                total: centsToDollars(quote.totalCents),
                vehicles: quote.vehicles.map((vehicle) => ({
                    ...vehicle,
                    servicePrice: centsToDollars(vehicle.servicePriceCents),
                    addOnsPrice: centsToDollars(vehicle.addOnsPriceCents),
                    total: centsToDollars(vehicle.totalCents),
                })),
            },
        }, { status: 409 });
    }

    const amountCents = quote.totalCents;
    if (amountCents <= 0) {
        return NextResponse.json({ error: 'Invalid booking total' }, { status: 400 });
    }
    const userId = user?.id || null;

    // Generate a group ID when booking multiple vehicles in one appointment
    const bookingGroupId = vehicleCount > 1 ? crypto.randomUUID() : null;

    // ── Step 1: Create booking(s) — one per vehicle ─────────────────────────
    const verifiedAddOns = quote.addOns.map((addOn) => ({
        id: addOn.id,
        name: addOn.name,
        price: centsToDollars(addOn.priceCents),
        price_cents: addOn.priceCents,
    }));
    const bookingRows = vehicles.map((v, index) => ({
        user_id: userId,
        status: 'pending_payment' as const,
        payment_status: 'unpaid' as const,
        date,
        time_window: timeWindow,
        address,
        city: city || '',
        state: state || 'FL',
        zip_code: zipCode,
        customer_name: customerName,
        customer_email: customerEmail,
        customer_phone: customerPhone || '',
        special_instructions: specialInstructions || '',
        locale,
        subtotal: formatCents(quote.vehicles[index].totalCents),
        service_fee: 0,
        total_amount: formatCents(quote.vehicles[index].totalCents),
        service_name: quote.service.name,
        service_id: quote.service.id,
        selected_add_ons: verifiedAddOns,
        vehicle_type: quote.vehicles[index].bodyStyle,
        vehicle_body_style: quote.vehicles[index].bodyStyle,
        service_price_cents: quote.vehicles[index].servicePriceCents,
        add_ons_price_cents: quote.vehicles[index].addOnsPriceCents,
        total_price_cents: quote.vehicles[index].totalCents,
        pricing_revision: quote.pricingRevision,
        vehicle_make: v.make || null,
        vehicle_model: v.model || null,
        vehicle_year: v.year || null,
        vehicle_color: v.color || null,
        ...(bookingGroupId ? { booking_group_id: bookingGroupId } : {}),
    }));

    const { data: bookings, error: bookingError } = await supabase
        .from('bookings')
        .insert(bookingRows)
        .select();

    if (bookingError || !bookings || bookings.length === 0) {
        console.error('create-with-payment: booking insert failed:', bookingError);
        return NextResponse.json({ error: 'Failed to create booking' }, { status: 500 });
    }

    const bookingIds = bookings.map(b => String(b.id));
    const primaryBookingId = bookingIds[0];

    // ── Step 2: Create Stripe PaymentIntent ──────────────────────────────────
    // If this fails, we delete all bookings so no orphaned records are left.
    let paymentIntent: { clientSecret: string | null; paymentIntentId: string; amount: number };
    try {
        paymentIntent = await createPaymentIntent({
            amount: amountCents,
            bookingId: primaryBookingId,
            customerId: user.id,
            currency,
            metadata: {
                serviceId: String(quote.service.id),
                bodyStyleSummary: summarizeBodyStyles(quote.vehicles.map((vehicle) => vehicle.bodyStyle)),
                vehicleCount: String(vehicleCount),
                pricingRevision: quote.pricingRevision,
            },
        });
    } catch (stripeErr) {
        // Rollback: remove all bookings we just created
        await supabase.from('bookings').delete().in('id', bookings.map(b => b.id));

        console.error('create-with-payment: Stripe failed, bookings rolled back:', stripeErr);
        return NextResponse.json(
            { error: 'Payment setup failed. Please try again or contact support.' },
            { status: 502 }
        );
    }

    // ── Step 3: Persist payment intent ID on all bookings ────────────────────
    await supabase
        .from('bookings')
        .update({ payment_intent_id: paymentIntent.paymentIntentId })
        .in('id', bookings.map(b => b.id));

    // ── Step 4: Customer confirmation email only ──────────────────────────────
    // Contractor notifications fire from the webhook (payment_intent.amount_capturable_updated)
    // AFTER payment is confirmed, so contractors only see jobs that have been paid for.
    notifyCustomer(bookings[0], quote.service.name).catch(
        (err) => {
            console.error('create-with-payment: customer notification failed:', err);
            Sentry.captureException(err, { tags: { context: 'customer_notification', bookingId: bookings[0].id } });
        }
    );

    // ── Step 5: Enqueue payment reminder emails via QStash ───────────────────
    // Each reminder fires only if the booking is still pending_payment at that time.
    schedulePaymentReminders(bookings[0].id).catch(
        (err) => console.error('create-with-payment: QStash scheduling failed:', err)
    );

    const confirmationCodes = bookings.map(b => b.confirmation_code);

    return NextResponse.json({
        success: true,
        confirmationCode: confirmationCodes[0],
        confirmationCodes,
        clientSecret: paymentIntent.clientSecret,
        paymentIntentId: paymentIntent.paymentIntentId,
        bookingId: primaryBookingId,
        bookingIds,
        bookingGroupId,
        vehicleCount,
        totalCents: quote.totalCents,
        pricingRevision: quote.pricingRevision,
    });
}

function summarizeBodyStyles(styles: Array<(typeof BODY_STYLES)[number]>): string {
    const counts = new Map<string, number>();
    for (const style of styles) counts.set(style, (counts.get(style) ?? 0) + 1);
    return [...counts.entries()]
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([style, count]) => `${style}:${count}`)
        .join(',');
}

// ── Schedule escalating payment reminders via Upstash QStash ─────────────────
// Delays: 15 min → 2 hours → 24 hours

async function schedulePaymentReminders(bookingId: number) {
    const qstash = getQStashClient();
    const url = `${SITE_URL}/api/booking/payment-reminder`;

    const reminders: Array<{ delay: number; reminderNumber: 1 | 2 | 3 }> = [
        { delay: 15 * 60,       reminderNumber: 1 }, // 15 minutes
        { delay: 2 * 60 * 60,   reminderNumber: 2 }, // 2 hours
        { delay: 24 * 60 * 60,  reminderNumber: 3 }, // 24 hours
    ];

    await Promise.all(
        reminders.map(({ delay, reminderNumber }) =>
            qstash.publishJSON({
                url,
                delay,
                body: { bookingId, reminderNumber },
            })
        )
    );

    console.log(`Payment reminders scheduled for booking ${bookingId}`);
}

// ── Customer confirmation email only (booking pending payment) ────────────────

async function notifyCustomer(
    booking: Record<string, unknown>,
    resolvedServiceName: string,
) {
    const bookingWithService = { ...booking, service_name: resolvedServiceName };
    const { notify } = await import('@/lib/notifications');
    await notify({ type: 'booking.created', booking: bookingWithService });
}
