import { createClient } from './client';
import { Database } from '@/types/database';

export type BookingInsert = Database['public']['Tables']['bookings']['Insert'];

// confirmation_code is now auto-generated by Postgres sequence (DEFAULT generate_booking_code())

/**
 */
function generateDocumentId(length = 24): string {
    const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
    let result = '';
    for (let i = 0; i < length; i++) {
        result += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return result;
}

/**
 * Creates a new booking in Supabase
 */
export async function createSupabaseBooking(data: {
    serviceId: number;
    addOnIds: number[];
    date: string;
    timeWindow: string;
    address: string;
    city: string;
    state: string;
    zipCode: string;
    customerName: string;
    customerEmail: string;
    customerPhone: string;
    specialInstructions?: string;
    subtotal: number;
    serviceFee: number;
    total: number;
    serviceName?: string;
    vehicleMake?: string;
    vehicleModel?: string;
    vehicleYear?: string;
    vehicleColor?: string;
}) {
    const supabase = createClient();

    const documentId = generateDocumentId();

    const bookingData: BookingInsert = {
        document_id: documentId,
        date: data.date,
        address: data.address,
        city: data.city,
        state: data.state,
        zip_code: data.zipCode,
        customer_name: data.customerName,
        customer_email: data.customerEmail,
        customer_phone: data.customerPhone,
        special_instructions: data.specialInstructions,
        total_amount: data.total,
        status: 'pending',
        payment_status: 'unpaid',
        time_window: data.timeWindow,
        service_name: data.serviceName || null,
        vehicle_make: data.vehicleMake || null,
        vehicle_model: data.vehicleModel || null,
        vehicle_year: data.vehicleYear || null,
        vehicle_color: data.vehicleColor || null,
        published_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    };

    // Explicitly casting for numeric fields if needed, though supabase-js usually handles it

    const { data: booking, error } = await supabase
        .from('bookings')
        .insert(bookingData)
        .select()
        .single();

    if (error) {
        console.error('Error creating booking:', error);
        throw error;
    }

    return booking;
}
